# Generated by Django 4.2.9 on 2026-02-24 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('is_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='facilities.branch')),
                ('current_operator', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_counter', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='facilities.service')),
            ],
            options={
                'db_table': 'waitfree_counter',
                'ordering': ['number'],
                'unique_together': {('number', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='OperatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('counter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='counters.counter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waitfree_operator_assignment',
            },
        ),
    ]
