# Generated by Django 4.2.9 on 2026-02-24 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Being Served'), ('served', 'Served'), ('no_show', 'No Show')], default='waiting', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('estimated_wait_time', models.IntegerField(default=0, help_text='Estimated wait time in minutes')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('no_show_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tickets', to='facilities.branch')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tickets', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tickets', to='facilities.service')),
            ],
            options={
                'db_table': 'waitfree_queue_ticket',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['service', 'status', 'joined_at'], name='waitfree_qu_service_db04cb_idx'), models.Index(fields=['branch', 'status'], name='waitfree_qu_branch__5950e6_idx'), models.Index(fields=['citizen', 'status'], name='waitfree_qu_citizen_8fb8a0_idx')],
            },
        ),
    ]
