# Generated by Django 4.2.9 on 2026-02-24 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_mobile', models.CharField(blank=True, max_length=15)),
                ('notification_type', models.CharField(choices=[('otp', 'OTP'), ('turn_alert', 'Turn Alert')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('retried', 'Retried')], default='sent', max_length=20)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waitfree_notification_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
